//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.02 at 11:57:04 PM SAMT 
//


package org.teomant.server;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.teomant.server package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.teomant.server
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDateTimeResponse }
     * 
     */
    public GetDateTimeResponse createGetDateTimeResponse() {
        return new GetDateTimeResponse();
    }

    /**
     * Create an instance of {@link GetDateTimeRequest }
     * 
     */
    public GetDateTimeRequest createGetDateTimeRequest() {
        return new GetDateTimeRequest();
    }

}
